# Generated by Django 4.0.1 on 2022-01-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_despesa_rename_category_tipodespesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='conta',
            field=models.CharField(default=3, max_length=266),
            preserve_default=False,
        ),
    ]
