# Generated by Django 4.0.1 on 2022-01-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_receita_conta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoConta',
        ),
        migrations.DeleteModel(
            name='tipoReceita',
        ),
    ]
