# Generated by Django 4.0 on 2022-01-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Usuario',
        ),
    ]
